# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: Checkout n8n
      uses: actions/checkout@v4
      with: 
        repository: n8n-io/n8n
        path: ./n8n
    - name: Checkout local
      uses: actions/checkout@v4
      with: 
        path: ./n8n-i18n-chinese

    - uses: actions/setup-node@v4.2.0
      with:
        node-version: 20.x

    - name: Setup corepack and pnpm
      run: |
        npm i -g corepack@0.31
        corepack enable

    - run: pnpm install --frozen-lockfile
      working-directory: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n

    - name: Move i18n zh-CN
      run: mv /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n-i18n-chinese/zh-CN.json /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n/packages/frontend/editor-ui/src/plugins/i18n/locales

    - name: Pnpm build frontend
      run: pnpm build:frontend
      working-directory: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n
