# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: Checkout n8n
      uses: actions/checkout@v4
      with: 
        repository: n8n-io/n8n
        path: ./n8n
        
    - name: Checkout local
      uses: actions/checkout@v4
      with: 
        path: ./n8n-i18n-chinese
        # 必须设置，不然 tags 拉不到
        fetch-depth: 0  
          
    - name: Fetch all tags
      run: git fetch --tags
      

    - name: Read version from package.json
      id: get_version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "Version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      working-directory: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n
          
    - name: Check if tag exists
      id: check_tag
      run: |
        TAG="n8n@${{ steps.get_version.outputs.version }}"
        echo "Checking for remote tag: $TAG"
        if git ls-remote --tags origin | grep -q "refs/tags/$TAG$"; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      working-directory: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n-i18n-chinese

    - name: Exit if tags exist
      if: steps.check_tag.outputs.exists == 'true'
      run: |
        echo "Tags exist, stopping workflow."
        exit 0

    - uses: actions/setup-node@v4.2.0
      with:
        node-version: 20.x

    - name: Setup corepack and pnpm
      run: |
        npm i -g corepack@0.31
        corepack enable

    - run: pnpm install --frozen-lockfile
      working-directory: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n

    - name: Move i18n zh-CN
      run: mv /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n-i18n-chinese/zh-CN.json /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n/packages/frontend/editor-ui/src/plugins/i18n/locales

    - name: Pnpm build editor-ui
      run: pnpm build
      working-directory: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n/packages/frontend/editor-ui

    - name: 打包 dist 产物
      run: |
        tar -czvf dist.tar.gz dist
      working-directory: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n/packages/frontend/editor-ui

    - name: 创建 GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: n8n@${{ steps.get_version.outputs.version }}
        name: Release editor-ui to n8n@${{ steps.get_version.outputs.version }}
        body: |
          自动发布的中文语言包版本。
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 上传 dist.tar.gz 到 Release
      uses: softprops/action-gh-release@v2
      with:
        files: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n/packages/frontend/editor-ui/dist.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
