# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: Checkout n8n
      uses: actions/checkout@v4
      with: 
        repository: n8n-io/n8n
    - name: Checkout local
      uses: actions/checkout@v4
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'pnpm'
    - name: Pnpm build
      run: pwd | cat
    - name: Move i18n zh-CN
      run: mv ./n8n-i18n-chinese/zh-CN.json ./n8n/packages/frontend/editor-ui/src/plugins/i18n/locales
    - name: Pnpm install
      run: corepack prepare --activate && npm install -g pnpm && pnpm install
      working-directory: ./n8n
    - name: Pnpm build
      run: corepack prepare --activate && pnpm build
      working-directory: ./n8n
