# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: Checkout n8n
      uses: actions/checkout@v4
      with: 
        repository: n8n-io/n8n
        path: ./n8n
        
    - name: Checkout local
      uses: actions/checkout@v4
      with: 
        path: ./n8n-i18n-chinese
        # 必须设置，不然 tags 拉不到
        fetch-depth: 0  
          
    - name: Fetch all tags
      run: git fetch --tags
      working-directory: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n-i18n-chinese

    - name: Read version from package.json
      id: get_version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "Version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      working-directory: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n
          
    - name: Check if tag exists
      id: check_tag
      run: |
        TAG="n8n@${{ steps.get_version.outputs.version }}"
        echo "Checking for tag: $TAG"
        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Exit if tags exist
      if: steps.check_tag.outputs.exists == 'true'
      run: |
        echo "Tags exist, stopping workflow."
        exit 0

    - uses: actions/setup-node@v4.2.0
      with:
        node-version: 20.x

    - name: Setup corepack and pnpm
      run: |
        npm i -g corepack@0.31
        corepack enable

    - run: pnpm install --frozen-lockfile
      working-directory: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n

    - name: Move i18n zh-CN
      run: mv /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n-i18n-chinese/zh-CN.json /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n/packages/frontend/editor-ui/src/plugins/i18n/locales

    - name: Pnpm build frontend
      run: pnpm build:frontend
      working-directory: /home/runner/work/n8n-i18n-chinese/n8n-i18n-chinese/n8n
