# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: Checkout n8n
      uses: actions/checkout@v4
      with: 
        repository: n8n-io/n8n
    - name: Checkout local
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Use pnpm
      uses: pnpm/action-setup@v4.1.0
    - run: mv /workspaces/n8n-i18n-chinese/zh-CN.json /workspaces/n8n/packages/frontend/editor-ui/src/plugins/i18n/locales
    - run: cd /workspaces/n8n && corepack prepare --activate && pnpm install
    - run: corepack prepare --activate && pnpm build
